version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "Admin"
      MYSQL_USER: "client"
      MYSQL_PASSWORD: "Admin"
      MYSQL_AUTHENTIFICATION_PLUGIN: mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - db