version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "Admin"
      MYSQL_USER: "client"
      MYSQL_PASSWORD: "Admin"
      MYSQL_DATABASE: "stamp3"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - stamp4_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - stamp4_network

  vuejs-app:
    build:
      context: ./stamp4
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - stamp4_network

  express-api:
    build:
      context: ./stamp-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - stamp4_network

networks:
  stamp4_network:
    driver: bridge
